version: '3'
services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
    - axonserver-data:/data
    - axonserver-events:/eventdata
    - axonserver-config:/config:ro
    ports:
    - "8024:8024"
    - "8124:8124"
    - "8224:8224"
    networks:
    - axon-server

volumes:
  axonserver-data:
    driver: local
  axonserver-events:
    driver: local
  axonserver-config:
    driver: local

networks:
  axon-server: